import { PLANS, PUBLIC_PLAN_ORDER, TRIAL_DAYS, annualSavingsPercent, formatLimit, usd, type PlanId } from '../plans';

// The assistant answers ONLY from this list (plus live plan data). Every statement here must be true of the
// product as it exists; where something is not built, the answer says so. Do not add marketing claims.
export type Link = { label: string; href: string };
export type Entry = { id: string; audience: 'public' | 'app' | 'both'; title: string; examples: string[]; keywords: string[]; answer: string; links?: Link[]; followups?: string[] };

const L = { pricing: { label: 'See pricing', href: '/pricing' }, access: { label: 'Request access', href: '/request-access' }, home: { label: 'How it works', href: '/#how-it-works' } };
const growth = PLANS.GROWTH;

export const ENTRIES: Entry[] = [
  { id: 'what', audience: 'both', title: 'What is LeadMelo', examples: ['what is leadmelo', 'what does this do', 'what do you do', 'tell me about the product', 'explain leadmelo'], keywords: ['product', 'platform', 'overview', 'autopilot', 'outbound', 'lead generation'],
    answer: 'LeadMelo runs outbound sales for you as a repeatable loop: you describe who you want to reach (an ideal customer profile), it finds matching companies and decision-makers, verifies their email addresses, sends your approved first email and timed follow-ups, stops the moment someone replies, answers clear "yes, let\'s talk" replies with your booking link, and records a meeting only when your calendar confirms the buyer actually booked a time.', links: [L.home, L.pricing], followups: ['how', 'guarantee'] },
  { id: 'how', audience: 'both', title: 'How it works step by step', examples: ['how does it work', 'how does leadmelo work', 'what are the steps', 'walk me through', 'process'], keywords: ['workflow', 'steps', 'pipeline', 'loop'],
    answer: '1) You define an ICP (industries, company sizes, regions, buyer titles, and a "hiring" signal). 2) You write the email sequence and pick a sender mailbox and a booking link. 3) LeadMelo finds and verifies prospects through your data provider; you can also add a prospect by hand for review. 4) It scores each one against your ICP and skips anyone suppressed or already contacted. 5) It sends within your daily caps and business hours, in review-first or automatic mode. 6) Replies are classified; unclear ones go to a person. 7) Meetings appear once the calendar confirms them, or when someone records one on Meetings.', links: [L.home], followups: ['modes', 'scheduling'] },
  { id: 'guarantee', audience: 'both', title: 'Do you guarantee meetings or leads', examples: ['can you promise i will get sales calls', 'can you assure me of results', 'do you guarantee meetings', 'will i see meetings appear', 'how many meetings will i get', 'guaranteed results', 'does it really work', 'roi'], keywords: ['guarantee', 'promise', 'results', 'conversion', 'sales calls', 'assure', 'ensure', 'realistic'],
    answer: 'No. Nobody can honestly guarantee meetings: results depend on your offer, your market, the quality of contact data, your sender reputation and whether buyers respond. LeadMelo is built to raise the odds and to measure what actually happens (replies, meetings booked, meetings attended), with copy experiments to improve it. It never counts a positive reply or a link click as a meeting.', followups: ['experiments', 'deliverability'] },
  { id: 'icp', audience: 'both', title: 'ICP and targeting', examples: ['what is an icp', 'what information do i give to set up a target audience', 'who exactly can i reach with this', 'ideal customer profile', 'how do i target', 'who can i target', 'targeting options', 'filters'], keywords: ['industry', 'company size', 'region', 'geography', 'titles', 'technology', 'signals', 'exclusions'],
    answer: 'An ICP holds industries, company-size bands, regions, buyer titles, technologies, buying signals and exclusions. Matching is exact and explainable: a prospect either fits your ICP wording or is skipped. Today the only buying signal LeadMelo can back with evidence from its bundled data source is "Hiring <role>" (an open job posting). You can create, edit, duplicate or deactivate an ICP, reuse one across campaigns, or define one inside a campaign.', followups: ['sources'] },
  { id: 'sources', audience: 'both', title: 'Where prospect data comes from', examples: ['where does the data come from', 'apollo', 'hunter', 'data provider', 'prospect database', 'do you have contacts', 'lead database'], keywords: ['source', 'enrichment', 'verification', 'gateway', 'contacts', 'emails'],
    answer: 'LeadMelo does not own a contact database. Discovery and email verification go through a provider gateway. A reference gateway for Apollo (search and enrichment) and Hunter (email verification) is included, written from those vendors\' documentation; it needs your own vendor accounts and has not yet been run against live accounts, so treat it as needing acceptance testing. You can also add or import prospects by hand (CSV) for review, or connect your own gateway that follows the published contract.', followups: ['email-providers'] },
  { id: 'email-providers', audience: 'both', title: 'Which mailboxes can send', examples: ['which email providers', 'which email systems work with this', 'microsoft 365', 'can i send from my outlook account', 'send from my own email address', 'gmail', 'google workspace', 'can i use gmail', 'smtp', 'sender mailbox'], keywords: ['mailbox', 'sender', 'office 365', 'exchange', 'graph', 'send', 'account', 'send from', 'own email'],
    answer: 'Microsoft 365 mailboxes are supported natively (sending, reply detection and reconciliation through Microsoft Graph, limited to mailboxes you allow-list). Google Workspace and plain SMTP are not built in yet; they would need a gateway that implements the send contract. LeadMelo never silently falls back to a different sender.', followups: ['deliverability'] },
  { id: 'scheduling', audience: 'both', title: 'Scheduling and Calendly', examples: ['how do meetings get booked', 'how do appointments get onto my calendar', 'calendly', 'calendar', 'scheduling link', 'do you book meetings'], keywords: ['booking', 'meeting', 'calendar', 'invitee', 'cancel', 'reschedule', 'schedule', 'appointments'],
    answer: 'When a buyer replies with clear interest, LeadMelo sends your campaign\'s Calendly link with a signed tag that ties the booking to the right campaign and contact. A meeting is recorded when Calendly\'s signed webhook confirms the booking, or when a person records one by hand on the Meetings page. Cancellations update it. Reschedules appear as a cancellation plus a new booking. Google and Microsoft calendars are not built in yet, and missed-webhook recovery needs the reconciliation job.', links: [{ label: 'How it works', href: '/#how-it-works' }] },
  { id: 'modes', audience: 'both', title: 'Approval and automation modes', examples: ['can i approve emails', 'review before sending', 'can someone read each email before it goes out', 'fully automatic', 'automation modes', 'human in the loop', 'control what gets sent'], keywords: ['approve', 'review', 'manual', 'automatic', 'approval', 'before it goes out', 'sign off', 'before sending'],
    answer: 'You choose per campaign: review every message before it sends, fully automatic, or automatic outreach with review of meeting qualification. On Automation you can turn built-in worker rules on or off and add a rule that pauses active campaigns when an event happens (bounce, failed booking, missed webhook). Any material edit to targeting or copy creates a new version and revokes earlier approvals. There is a global emergency stop and a per-tenant stop.', followups: ['safety'] },
  { id: 'replies', audience: 'both', title: 'How replies are handled', examples: ['what happens when someone replies', 'what if a prospect writes back saying no', 'someone responds that they are not interested', 'reply handling', 'negative replies', 'out of office', 'unsubscribe replies', 'positive reply'], keywords: ['reply', 'response', 'interested', 'objection', 'referral', 'classification', 'not interested', 'says no', 'writes back', 'answers'],
    answer: 'Any reply stops the sequence for that person. Clear opt-outs suppress them permanently. A clear positive reply queues one booking-link email. Questions, objections, referrals, out-of-office, bounce notices and anything ambiguous are held for a person, who can mark the reply positive, suppress the sender, or dismiss it. The classifier is rule-based and deliberately conservative; it is not an AI that negotiates for you.', followups: ['safety'] },
  { id: 'ai-assist', audience: 'both', title: 'Optional AI assist', examples: ['do you use ai', 'is there ai in leadmelo', 'can i use my own ai model', 'does it work with ollama', 'ai generated emails', 'ai email copy', 'chatgpt', 'llm'], keywords: ['ai', 'llm', 'ollama', 'openai', 'model', 'artificial intelligence', 'gpt', 'copilot'],
    answer: 'AI assist is optional and off by default. If an admin connects a model (Ollama or any OpenAI-compatible service, with their own key), LeadMelo can draft an ICP and email sequence from a plain description and summarise replies with a suggested response. Everything it writes is a draft that a person reviews: it never sends email, never changes who is suppressed, and opt-outs are always decided by the built-in rules. Prospect and reply text is sent to the model you choose.', followups: ['replies', 'safety'] },
  { id: 'safety', audience: 'both', title: 'Safety and compliance controls', examples: ['is it compliant', 'can-spam', 'gdpr', 'unsubscribe', 'compliance', 'spam', 'legal'], keywords: ['opt-out', 'suppression', 'postal address', 'privacy', 'consent', 'law'],
    answer: 'Built in: a working unsubscribe link and one-click header on every email, your postal address in the footer, a permanent suppression list checked again immediately before each send, caps per day and week, business-hour windows, and data export and erasure for a person on request. This is tooling, not legal advice: you are responsible for your lawful basis, your target regions and your content, and you should have counsel review your setup.', followups: ['security'] },
  { id: 'security', audience: 'both', title: 'Security', examples: ['is my data safe', 'how is my customer information protected', 'security', 'encryption', 'mfa', 'two factor', 'certification', 'soc 2', 'iso 27001'], keywords: ['secure', 'encrypted', 'isolation', 'tenant', 'audit', 'password'],
    answer: 'Each tenant\'s data is isolated in the application and by database triggers that reject cross-tenant references. Credentials and secrets are encrypted at rest (AES-256-GCM), passwords use salted scrypt, sessions expire, and two-factor authentication (TOTP with recovery codes) is available. There is no SOC 2 or ISO 27001 certification and no independent penetration test yet; do not treat the product as certified.', followups: ['hosting'] },
  { id: 'hosting', audience: 'both', title: 'Hosting and self-hosting', examples: ['where is it hosted', 'where can this be deployed', 'self host', 'on premise', 'can i run this on my own servers', 'install it on our infrastructure', 'docker', 'data location', 'can i host it myself'], keywords: ['server', 'deployment', 'cloud', 'region', 'postgres', 'run', 'own', 'install', 'infrastructure'],
    answer: 'LeadMelo is built to run on your own Linux server or any Docker host with PostgreSQL 16; nothing requires a specific cloud. The package includes a deployment runbook, encrypted offsite backup and restore scripts, and reverse-proxy examples. These have been tested with stub tools and structural checks, and still need a real backup and restore drill on your server.', followups: ['security'] },
  { id: 'deliverability', audience: 'both', title: 'Deliverability', examples: ['deliverability', 'will my emails land in spam', 'sender reputation', 'spf dkim dmarc', 'warm up', 'bounce rate', 'inbox placement'], keywords: ['reputation', 'spam folder', 'bounce', 'complaint', 'domain', 'authentication', 'ramp'],
    answer: 'LeadMelo checks that the sending domain publishes SPF and DMARC, watches bounce and complaint rates from your own sends, blocks a sender that crosses thresholds, and ramps daily volume up gradually for new senders. It cannot promise inbox placement; that depends on your domain, content and list quality.', followups: ['email-providers'] },
  { id: 'experiments', audience: 'both', title: 'A/B tests and improvement', examples: ['ab testing', 'experiments', 'improve results', 'test subject lines', 'optimization', 'learning'], keywords: ['variant', 'copy test', 'winner', 'statistics', 'subject'],
    answer: 'You can test alternative subject and body copy on one email step. Assignment is stable and recorded, a winner needs a minimum sample and statistical significance, and an unsubscribe check can block a winner that annoys people. LeadMelo only recommends; a person accepts or rejects. It tests copy only, not targeting or timing, and there is no control group that receives nothing.', followups: ['guarantee'] },
  { id: 'analytics', audience: 'both', title: 'Reporting and digest', examples: ['reporting', 'analytics', 'dashboard', 'metrics', 'daily summary', 'digest'], keywords: ['stats', 'numbers', 'activity', 'meetings booked'],
    answer: 'The workspace shows upcoming meetings and activity for the last 24 hours, 7 days or 30 days (emails sent, replies, positive replies, meetings booked or cancelled), open alerts that need a person, and this month\'s provider spend. Numbers come from saved records only. There is no scheduled email digest yet.' },
  { id: 'team', audience: 'both', title: 'Users, roles and invitations', examples: ['add team members', 'how many people from my company can log in', 'can i add colleagues and control what they can do', 'user roles and permissions', 'seats', 'invite users', 'sso', 'single sign on'], keywords: ['user', 'admin', 'manager', 'member', 'invitation', 'colleagues', 'control', 'access'],
    answer: 'Roles are administrator, manager (runs campaigns) and member (views). An administrator creates a one-time invitation link and delivers it; LeadMelo does not send email itself. Two-factor authentication is optional per user. Google or Microsoft single sign-on is not built yet.' },
  { id: 'mobile', audience: 'both', title: 'Mobile and installable app', examples: ['mobile app', 'ios', 'android', 'install on phone', 'pwa', 'works on mobile', 'progressive web app', 'tablet'], keywords: ['phone', 'responsive', 'home screen', 'offline'],
    answer: 'LeadMelo works in any modern mobile browser and can be installed to your home screen as a progressive web app (in Safari use Share, then Add to Home Screen; in Chrome or Edge use the Install button). Only static files are cached for speed. Your data and signed-in pages are never stored offline, so an offline visit shows a simple offline page.' },
  { id: 'themes', audience: 'both', title: 'Themes and appearance', examples: ['dark mode', 'a night mode for the interface', 'change theme', 'themes', 'colors', 'appearance', 'light mode'], keywords: ['dark', 'light', 'ocean', 'forest', 'sunset', 'look'],
    answer: 'Settings, then Appearance, lets each person choose System, Light, Dark, Ocean, Forest or Sunset. The choice follows your account across devices, and every theme is contrast-checked for readable text.' },
  { id: 'trial', audience: 'public', title: 'Free trial', examples: ['is there a free trial', 'is there a way to try before i buy', 'trial', 'try it free', 'demo', 'free plan', 'test it'], keywords: ['free', 'try', 'sandbox', 'evaluate'],
    answer: `The Trial plan lasts ${TRIAL_DAYS} days with 1 active campaign, ${formatLimit(PLANS.FREE.limits.monthlyEmails)} emails and ${formatLimit(PLANS.FREE.limits.monthlyProspects)} prospects a month, and review-first sending. Workspaces are provisioned by our team: request access and we will set one up. There is no self-service signup yet.`, links: [L.access] },
  { id: 'payment', audience: 'public', title: 'Payment and billing', examples: ['how do i pay', 'billing', 'invoice', 'credit card', 'payment methods', 'checkout', 'cancel subscription', 'refund'], keywords: ['pay', 'subscribe', 'stripe', 'purchase', 'cancel'],
    answer: 'Online checkout is not live yet. Paid plans are set up by our team after you request access, and plan limits are then enforced in the product. Ask us about invoicing, cancellation and refund terms when you request access; I do not have those terms.', links: [L.access] },
  { id: 'api', audience: 'both', title: 'API and integrations', examples: ['is there an api', 'does it plug into other tools i use', 'api access', 'webhooks', 'zapier', 'crm', 'salesforce', 'hubspot', 'integrations'], keywords: ['integration', 'connect', 'export', 'rest'],
    answer: 'There is no public API or CRM sync yet. Integrations that exist: Microsoft 365 mail, Calendly bookings, the Apollo and Hunter reference gateway, signed inbound events, and an outbound alert webhook. Prospect data can be exported per person on request.' },
  { id: 'support', audience: 'public', title: 'Support and contact', examples: ['contact support', 'talk to a human', 'talk to sales', 'speak to someone', 'customer service', 'help', 'email you'], keywords: ['human', 'sales', 'person', 'agent', 'call', 'demo'],
    answer: 'I can pass your question to the team. Leave your name and email and we will reply. I do not have live phone or chat staff on this page.', links: [L.access] },
  { id: 'status', audience: 'public', title: 'Product maturity', examples: ['is it production ready', 'is this ready', 'early access', 'beta', 'maturity', 'customers', 'case studies', 'reviews'], keywords: ['stable', 'launch', 'pilot', 'references'],
    answer: 'LeadMelo is an early-access engineering pilot. It has automated tests, but it has not yet been run against live Microsoft, Calendly, Apollo or Hunter accounts or under load, and I have no customer case studies to show. Expect to start with small volumes and review-first sending.' },
  { id: 'limits-what', audience: 'both', title: 'What plan limits mean', examples: ['what counts as an active campaign', 'what is a seat', 'limits explained', 'what happens when i hit my limit', 'overage'], keywords: ['quota', 'cap', 'exceed', 'allowance'],
    answer: 'Active campaigns are campaigns currently running. Seats are users plus pending invitations. Emails are sequence emails sent in the calendar month; replies you send to interested buyers are never blocked by the plan. Prospects are people bought from your data provider in the month. When a limit is reached, that action pauses or is refused with a clear message until next month or a plan change; nothing is silently dropped.' },
  // ---- signed-in help ----
  { id: 'app-start', audience: 'app', title: 'Getting started checklist', examples: ['how do i get started', 'setup', 'first campaign', 'onboarding', 'set up'], keywords: ['begin', 'first', 'configure', 'checklist'],
    answer: 'Suggested order: 1) Settings: enable automation, add your postal address and the gateway credential. 2) Settings: connect Microsoft 365 and add the Calendly signing key. 3) Create an ICP and a campaign in review-before-send mode. 4) Make sure sender health is recorded. 5) Activate; the page tells you exactly what is missing if a check fails. 6) Approve the first messages in Automation.', links: [{ label: 'Open settings', href: '/app/settings' }, { label: 'Campaigns', href: '/app/campaigns' }] },
  { id: 'app-not-sending', audience: 'app', title: 'Why is my campaign not sending', examples: ['why is my campaign not sending', 'no emails sent', 'campaign stuck', 'nothing is happening', 'not sending', 'activation blocked'], keywords: ['blocked', 'paused', 'queued', 'stuck', 'readiness'],
    answer: 'The usual causes, in order: outbound sending is switched off by the operator; tenant automation is off; no fresh sender health (needs a HEALTHY status under 24 hours old); your postal address is missing; the mailbox connection or reply sync is unhealthy; review-before-send mode is waiting for your approval; a daily cap or send window (hours, weekends, holidays) applies; or your plan limit is reached. Activation shows the exact blocker; the Automation page shows queued messages and their status.', links: [{ label: 'Automation', href: '/app/autopilot' }] },
  { id: 'app-no-meetings', audience: 'app', title: 'Why no meetings yet', examples: ['why no meetings', 'no replies', 'low replies', 'no appointments yet', 'how to improve results'], keywords: ['results', 'reply rate', 'improve', 'meetings'],
    answer: 'Check in this order: are emails actually being sent (Automation and the last-24-hours cards)? Are they landing (bounce rate, sender health)? Is the ICP matching the right buyers? Is the offer and first line specific? Then test one copy change with an experiment once you have a few hundred sends. Small volumes give noisy results; do not judge before roughly 100 sends per variant.' },
  { id: 'app-mfa', audience: 'app', title: 'Turn on two-factor authentication', examples: ['enable mfa', 'two factor authentication', 'authenticator app', '2fa', 'recovery codes'], keywords: ['totp', 'security', 'login'],
    answer: 'Settings, then "Your sign-in security", then "Set up two-factor authentication". Add the key to an authenticator app, enter the 6-digit code, and save the recovery codes shown once; each works one time.', links: [{ label: 'Open settings', href: '/app/settings' }] },
  { id: 'app-invite', audience: 'app', title: 'Invite a teammate', examples: ['invite a user', 'let a new employee into my workspace', 'add a teammate', 'reset a password', 'add someone to my team'], keywords: ['invitation', 'link', 'reset', 'seat'],
    answer: 'Settings, then Team: enter their email and a role, create the invitation, and send them the one-time link yourself (valid 72 hours). To reset a password, issue a one-time reset link for that person from the same table; it signs them out everywhere.', links: [{ label: 'Open settings', href: '/app/settings' }] },
  { id: 'app-privacy', audience: 'app', title: 'Export or erase a person\'s data', examples: ['delete a contact', 'gdpr request', 'erase data', 'export data', 'right to be forgotten', 'data subject request'], keywords: ['erasure', 'privacy', 'personal data', 'dsar'],
    answer: 'Settings, then "Privacy requests": Export shows everything held about an email address; Erase removes the person\'s record, replies and message text and permanently suppresses the address. Erasure cannot be undone. Both are administrator-only.', links: [{ label: 'Open settings', href: '/app/settings' }] },
  { id: 'app-connect', audience: 'app', title: 'Connect Microsoft 365 and Calendly', examples: ['connect microsoft', 'connect outlook', 'connect calendly', 'webhook setup', 'signing key'], keywords: ['graph', 'azure', 'app registration', 'webhook'],
    answer: 'Microsoft 365: Settings, then Microsoft 365, using an app registration limited to the mailboxes you allow-list; follow docs/MICROSOFT_365.md. Calendly: create a webhook subscription pointing at your workspace\'s Calendly webhook URL with a signing key, then save the same key in Settings; follow docs/CALENDLY.md. Both need a live acceptance test before unattended use.' }
];

// ---- live plan answers (generated from lib/plans.ts so they cannot drift) ----
const planLine = (id: PlanId) => {
  const p = PLANS[id];
  const price = p.monthlyUsd === null ? 'custom pricing' : p.monthlyUsd === 0 ? 'free' : `${usd(p.monthlyUsd)} per month, or ${usd(p.annualUsd!)} per year (${annualSavingsPercent(p)}% less)`;
  return `${p.name}: ${p.id === 'FREE' ? `free for ${TRIAL_DAYS} days` : price}. ${p.limits.activeCampaigns === -1 ? 'Unlimited' : p.limits.activeCampaigns} active campaigns, ${formatLimit(p.limits.monthlyEmails)} emails and ${formatLimit(p.limits.monthlyProspects)} prospects a month, ${formatLimit(p.limits.seats)} seats, ${formatLimit(p.limits.senders)} sender mailboxes.`;
};
export const planOverview = () => `Plans (illustrative prices, confirm when you request access): ${PUBLIC_PLAN_ORDER.map(planLine).join(' ')} ${growth.name} is the most popular.`;
export const planDetail = (id: PlanId) => `${planLine(id)} Includes: ${PLANS[id].features.join('; ')}.`;
export { planLine };
